
const Admin = require("../models/admin.model");
const Timetable = require("../models/timetable.model");

// Get all generated timetables with details for admin panel
const getAllTimetablesForAdmin = async (req, res) => {
  try {
    // Only show timetables generated by the logged-in admin
    const adminId = req.user.id;
    if (!adminId) return res.status(401).json({ error: "Unauthorized" });
    const timetables = await Timetable.find({ createdBy: adminId })
      .select('collegeName branchName workingDays classTimes createdAt');
    res.status(200).json({
      total: timetables.length,
      timetables,
    });
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch timetables", details: error.message });
  }
};

module.exports = {
  getAllTimetablesForAdmin,
};